// import "./src/basic/1"
// import "./src/basic/2"
// import "./src/basic/3"
// import "./src/basic/4"
// import "./src/basic/5"
// import "./src/basic/6"

// import "./src/generics/1"
// import "./src/generics/2"
// import "./src/generics/3"
// import "./src/generics/4"
// import "./src/generics/5"
// import "./src/generics/6"